### ISSUE TITLE
Implementation of 'self imitation learning'

### ISSUE THREAD

**Issue by rwightman** [ikostrikov/pytorch-a2c-ppo-acktr-gail#134]
I've been hacking around with an implementation of SIL on your codebase. Inspired by this paper (https://arxiv.org/abs/1806.05635) and code (https://github.com/junhyukoh/self-imitation-learning)

It's basically a prioritized replay buffer used to make off-policy updates that complement the on-policy updates for PG actor-critic algorithms to improve their sample efficiency (and sometimes absolute performance).

My initial impl is at https://github.com/rwightman/pytorch-a2c-ppo-acktr/commits/self-imitation-learning

Right now I'm having some success speeding up training performance in an environment with an insanely slow simulator (OpenSim). I'm open to running more specific tests and doing cleanup if you're interested in a PR at some point. I have not yet done significant tests, comparisons, or hyperparam searches at this stage.

**Comment by ikostrikov** [comment]
I've just read the paper. It looks really interesting. I was thinking about adding soft q learning and other off-policy algorithms.

I need some time to take a look at your implementation.

**Comment by rwightman** [comment]
Yeah, definitely no urgency. I'll keep a version of it on that branch. Likely some bugs to be found and tuning to do.
