### ISSUE TITLE
Observation Space Consistence Problem and Customize WarpFrame to use RGB observations

### ISSUE THREAD

**Issue by KarlXing** [ikostrikov/pytorch-a2c-ppo-acktr-gail#147]
Hi everyone. I'm trying to use A2C on MsPacman. I noticed that in wrap_deepmind, the RGB images will be converted into gray image and the size will be cut to 84*84. I'm trying to use original RGB images as the observation. In this process, I'm confused about several points. I really appreciate it if someone can help me.

1. Firstly, I tried to convert 210x160x3 RGB images to 210x160 gray image. The customized code is like below. I noticed that the observation space is not consistent with the frame. Since the width and height in deepmind wrapper are both 84, this problem may be ignored. I changed the WarpFrame and TransposeImage class like below.

```
class WarpFrameCarl(gym.ObservationWrapper):
    def __init__(self, env):
        gym.ObservationWrapper.__init__(self, env)
        self.width = 160
        self.height = 210
        self.observation_space = spaces.Box(low=0, high=255,
            shape=(self.height, self.width, 1), dtype=np.uint8)

    def observation(self, frame):
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
        return frame[:,:,None]

class TransposeImage(gym.ObservationWrapper):
    def __init__(self, env=None):
        super(TransposeImage, self).__init__(env)
        obs_shape = self.observation_space.shape
        self.observation_space = Box(
            self.observation_space.low[0, 0, 0],
            self.observation_space.high[0, 0, 0],
            [obs_shape[2], obs_shape[0], obs_shape[1]],
            dtype=self.observation_space.dtype)

    def observation(self, observation):
        return observation.transpose(2, 0, 1)
```
When I extract the the observation from rollout, it's correct.
![gray](https://user-images.githubusercontent.com/15907990/48022902-34a88680-e0f1-11e8-912d-6e30599430e2.png)

2. However, if I tried to use RGB images. I changed the WarpFrame like below:

```
class WarpFrameCarl(gym.ObservationWrapper):
    def __init__(self, env):
        gym.ObservationWrapper.__init__(self, env)
        self.width = 160
        self.height = 210
        self.observation_space = spaces.Box(low=0, high=255,
            shape=(self.height, self.width, 3), dtype=np.uint8)

    def observation(self, frame):
        # frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
        return frame
```

The observation I extracted from rollout storage is this: 

![rgb](https://user-images.githubusercontent.com/15907990/48023053-99fc7780-e0f1-11e8-9d20-d3be47b2890c.png)

Is there anyone familiar with that part?

**Comment by NiranthS** [comment]
Can you please check the correct order of the image returned. Is it RGB or BGR? 
cv2 user BGR format by default I guess

**Comment by KarlXing** [comment]
Hi @NiranthS, thank you for your answer! However, if it's just the problem of format like RGB or BGR, I think we should still see the correct patterns with different coloring. Since it was some work long time ago and I don't remember the exact details of my customization, I will close it.

**Comment by NiranthS** [comment]
Okay👍
