### ISSUE TITLE
Segmentation fault (core dumped)，run python main.py error

### ISSUE THREAD

**Issue by YuyangSunshine** [ikostrikov/pytorch-a2c-ppo-acktr-gail#172]
Follow the requiremets.

When I ran python main.py --env-name "PongNoFrameskip-v4", there were  a error as:

> Segmentation fault (core dumped).

I have ran every training. However, this error also performed.

**Comment by ikostrikov** [comment]
I cannot reproduce the error. Could you provide more details?
