### ISSUE TITLE
With which version of code is the benchmark curve generated?

### ISSUE THREAD

**Issue by ktlichkid** [ikostrikov/pytorch-a2c-ppo-acktr-gail#175]
Hi dear Ilya,

I have been investigating your implementation of A2C and want to reproduce some of the benchmark curves. Since the master branch is iterating very fast, could you please tell me which version (revision number of a stable version maybe?) did you use to generate the curves you attached in the Readme file? It would be great help to me.

Also, you mentioned that 
> I tried to reproduce OpenAI results as closely as possible.

in your Readme file too. OpenAI baseline's head version is also changing very fast, which revision of OpenAI baseline did you use as your benchmark?

Thank you so much for answering!! Really appreciate your help.

**Comment by ikostrikov** [comment]
I would try the versions of this repo and baselines that were the latest one when the images where uploaded.

**Comment by ktlichkid** [comment]
Thanks for you quick response. I'll try them
