### ISSUE TITLE
Weight Initialization for MLP

### ISSUE THREAD

**Issue by jmichaux** [ikostrikov/pytorch-a2c-ppo-acktr-gail#178]
Is there a reason sqrt(2) (1.414) is used as the gain value for initializing the layers in the MLP on [line 206](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/8a4a500b8bd7a7c10f7b3fbcaebcfdb6d62ef7d4/a2c_ppo_acktr/model.py#L206)?  According to [this](https://pytorch.org/docs/stable/_modules/torch/nn/init.html), the gain value for Tanh is 5.0 / 3 (1.67).

The numbers are fairly close, so I'm not sure it matters all that much?

**Comment by ikostrikov** [comment]
Yes, it should have been 5.0 / 3.0, but probably it doesn't matter too much.
