### ISSUE TITLE
a2c with mujoco

### ISSUE THREAD

**Issue by NishanthVAnand** [ikostrikov/pytorch-a2c-ppo-acktr-gail#189]
The default hyperparameters work well on ALE tasks but not on mujoco. I think the hyperparameters for mujoco are different. Could you tell me what hyperparameters to use while using mujoco tasks to get results reported in the PPO paper (https://arxiv.org/abs/1707.06347).

**Comment by ikostrikov** [comment]
As far as I know hyperparameters for A2C for mujoco are lost: https://github.com/openai/baselines/issues/125

**Comment by araffin** [comment]
Related: https://github.com/hill-a/stable-baselines/issues/249
