### ISSUE TITLE
possible a bug in storage.py on the index of recurrent_hidden_states

### ISSUE THREAD

**Issue by Kabibi** [ikostrikov/pytorch-a2c-ppo-acktr-gail#190]
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/d4c68c1ce8d87a7c4ae7a7d88b54daa197785fc4/a2c_ppo_acktr/storage.py#L167

It seems awkward. I think it should be 
`self.recurrent_hidden_state[:-1, ind])`.

**Comment by ikostrikov** [comment]
We need to store only the first hidden states. Others will be recomputed.
