### ISSUE TITLE
Summary explanation of recurrent hidden states and masks?

### ISSUE THREAD

**Issue by mattroos** [ikostrikov/pytorch-a2c-ppo-acktr-gail#193]
I'm trying to understand the implementation of the hidden states and masks in the recurrent policy (say, using the MLPBase). There has been some commentary on it, e.g., in #82 and #52. Maybe @ikostrikov, @maximecb, @dineshj1, and/or @timmeinhardt can provide a summary? Perhaps these specific questions will help facilitate a summary construction...

1. How are the hidden states maintained and across agents/environments, and updated with each step?
2. What is the role of the masks? (That is, *what* is being masked?)
3. What is being done in ```NNBase._forward_gru()``` versus what is being done in ```rollouts``` (```RollingStorage```)?
4. Are hidden states reset to zero when the environment/agent is ```done```? If so, where in the code are they reset?

**Comment by ikostrikov** [comment]
1. We compute hidden states during the rollout step in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/master/main.py#L114
2. Masks correspond to done states. 
3. In done we recompute the hidden states (it's done for simplicity). Thus, we need to provide the hidden states only for the first timesteps in a batch.
4. Resets are performed in the vectorized wrapper: https://github.com/openai/baselines/blob/master/baselines/common/vec_env/dummy_vec_env.py#L52

**Comment by mattroos** [comment]
Ok, that's helpful. Thanks!  I'm working through it but don't have a full understanding yet.

In the ```agent.update()``` call at https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/master/main.py#L158 we eventually get to the ```NNBase._forward_gru()``` call at https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/master/a2c_ppo_acktr/model.py#L111. In that case the sizes of the arguments are:
```
x.shape == [num_steps*num_processes, recurrent_input_size]
hxs.shape == [num_processes, hidden_size]
masks.shape == [num_steps*num_processes, 1]
```
Why is there only one hidden state vector for each processor, rather than for each step and processor?

As an aside, my goal is to build a policy network composed of a CNN followed by an RNN. Do you see any difficulties to implementing this in your framework? What if I wanted an RNN with more than one layer?

**Comment by Omegastick** [comment]
@mattroos You only need one set of hidden states because you only care about the hidden state on the first timestep. Hidden states after that will be generated by that function.

CNN followed by an RNN is no problem in this repo. In fact, it's the default if you train on an Atari env.

**Comment by ikostrikov** [comment]
@mattroos Sorry that I took me so long to reply.

It saves only 1 step because it recomputes the other for the computational graph.

It should be relatively easy to implement. You just need to modify the size of hidden dims and then just split them for multiple layers.

**Comment by mattroos** [comment]
Ok. Thanks to @Omegastick and @ikostrikov!!
