### ISSUE TITLE
PPO2: GPU-optimized version of PPO

### ISSUE THREAD

**Issue by SunHaozhe** [ikostrikov/pytorch-a2c-ppo-acktr-gail#196]
Does the current PPO implementation follow OpenAI's PPO2 implementation (https://github.com/openai/baselines/blob/master/baselines/ppo2/ppo2.py) ? In addition to value function clipping as reported in #136   , OpenAI's PPO2 has also been made to be GPU-optimized.

If the current PPO implementation is not GPU-optimized as OpenAI's PPO2, do you have plan to adjust this ?

**Comment by ikostrikov** [comment]
Yes, the current implementation corresponds to PPO2 and is GPU optimized.
