### ISSUE TITLE
A PyTorch Bug in envs.py

### ISSUE THREAD

**Issue by Shengyu-Feng** [ikostrikov/pytorch-a2c-ppo-acktr-gail#226]
For these two lines, 
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/blob/62e8d5896db155839056deb0fe60e0c05db0bf16/a2c_ppo_acktr/envs.py#L234-L235

should be 
`self.stacked_obs[:, :-self.shape_dim0] = self.stacked_obs[:, self.shape_dim0:].clone()`
because there's a PyTorch bug here.

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail/commit/84a7582477fb0d5c82ad6d850fe476829dddd2e1
