### ISSUE TITLE
get different results when I set the same seed

### ISSUE THREAD

**Issue by naivety77** [ikostrikov/pytorch-a2c-ppo-acktr-gail#237]
Dear Author,
When I run PPO, I notice that sometimes I would get different results when I set the same random seed.  It happens when I use multiple workers in Atari, however, the result is always fixed when I use a single worker in Mujoco. So I guess multiprocess might be the problem? I wonder how could I fix the final result with multiple workers in Atari, thank you!

**Comment by naivety77** [comment]
I tried to use a single worker in Atari just now and it also shows different results...

**Comment by ikostrikov** [comment]
Hi @naivety77 !

Did you set the flag cuda_deterministic to True?

Asynchronous execution on GPU is usually the main reason under getting different results for different runs.

**Comment by naivety77** [comment]
> Hi @naivety77 !
> 
> Did you set the flag cuda_deterministic to True?
> 
> Asynchronous execution on GPU is usually the main reason under getting different results for different runs.

It works, thanks for your reply! I forgot to change the default of cuda_deterministic in arguments before...
