### ISSUE TITLE
Usage of gradient penalty without Wasserstein Loss

### ISSUE THREAD

**Issue by mayankg95** [ikostrikov/pytorch-a2c-ppo-acktr-gail#240]
Could you explain why you have used gradient penalty without Wasserstein loss?

**Comment by ikostrikov** [comment]
I followed recommendations from [here](http://proceedings.mlr.press/v97/kurach19a/kurach19a.pdf):

In particular,

> Our fair and thorough empirical evaluation suggests that when the computational budget is limited one should consider non-saturating GAN loss and spectral normalization as default choices when applying GANs to a new dataset. Given additional computational budget, we suggest adding the gradient penalty from Gulrajani et al. (2017) and training the model until convergence.

Since computing GP is cheap in this case, I used the second suggestion.
