### ISSUE TITLE
Does setting the flag "use-proper-time-limits" to be True recommended for all gym environments with time limit?

### ISSUE THREAD

**Issue by PeixinC** [ikostrikov/pytorch-a2c-ppo-acktr-gail#259]
It seems to me that this flag should be set to True whenever an environment has a max episode time limit. To make this flag effective, the original env should be wrapped with a TimeLimitMask gym wrapper. However, line 47-48 in envs.py suggests that the wrapper will be applied only when the env class name contains the string 'TimeLimit'. Could you explain why? Thank you!

**Comment by ikostrikov** [comment]
Yes, with all environments with TimeLimit and truncated episodes.
